//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImarRuhsatTakipApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvuru
    {
        public int Id { get; set; }
        public int Basvuru_Turleri_Id { get; set; }
        public long Referans_kod { get; set; }
        public string Mal_Sahibi_Ad_Soyad { get; set; }
        public int Yapi_Denetim_Firmasi_Id { get; set; }
        public int Muteahhit_Id { get; set; }
        public int Talep_Tipleri_Id { get; set; }
        public int Durum_Id { get; set; }
        public string Aciklama { get; set; }
        public int Kullanicilar_Id { get; set; }
        public Nullable<System.DateTime> Dilekce_Tarihi { get; set; }
    
        public virtual Basvuru_Turleri Basvuru_Turleri { get; set; }
        public virtual Durumlar Durumlar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Muteahhit Muteahhit { get; set; }
        public virtual Talep_Tipleri Talep_Tipleri { get; set; }
        public virtual Yapi_Denetim_Firmasi Yapi_Denetim_Firmasi { get; set; }
    }
}
