//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImarRuhsatTakipApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImarRuhsatTakipAppDb2Entities : DbContext
    {
        public ImarRuhsatTakipAppDb2Entities()
            : base("name=ImarRuhsatTakipAppDb2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basvuru> Basvuru { get; set; }
        public virtual DbSet<Basvuru_Turleri> Basvuru_Turleri { get; set; }
        public virtual DbSet<Durumlar> Durumlar { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Muteahhit> Muteahhit { get; set; }
        public virtual DbSet<Sabitler> Sabitler { get; set; }
        public virtual DbSet<Talep_Tipleri> Talep_Tipleri { get; set; }
        public virtual DbSet<Yapi_Denetim_Firmasi> Yapi_Denetim_Firmasi { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
    }
}
